# ==============================================================================
# mise 設定
# ==============================================================================
# - https://mise.jdx.dev/

# 使用するツール・ランタイム
[tools]
node = "lts"
python = "latest"
rust = "stable"
