# ==============================================================================
# Starship 設定
# ==============================================================================
# - https://starship.rs/

"$schema" = "https://starship.rs/config-schema.json"
